name: Build, Test, and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js (for tooling)
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies (if package.json exists)
      run: |
        if [ -f package.json ]; then
          npm ci
        else
          echo "No package.json found, using static files"
        fi

    - name: Validate HTML
      run: |
        echo "Validating HTML files..."
        for file in *.html; do
          if [ -f "$file" ]; then
            echo "Found HTML file: $file"
            if grep -q "<!DOCTYPE\|<html\|<head\|<body" "$file"; then
              echo "✓ $file appears to be valid HTML"
            else
              echo "⚠ $file may not be valid HTML"
            fi
          fi
        done

    - name: Test JavaScript
      run: |
        echo "Testing JavaScript files..."
        for file in *.js; do
          if [ -f "$file" ]; then
            node -c "$file" && echo "✓ $file syntax OK" || echo "✗ $file has syntax errors"
          fi
        done

    - name: Run custom tests (if available)
      run: |
        if [ -f test.js ] && [ -f package.json ]; then
          npm test
        elif [ -f test.html ]; then
          echo "HTML test file found - manual testing required"
        else
          echo "No automated tests found"
        fi

    - name: Build (if build script exists)
      run: |
        if [ -f package.json ] && npm run build --if-present; then
          echo "Build completed"
        else
          echo "No build script found, using files as-is"
        fi

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
